const char *ui_builtin_menu = 
"background #3f6da070\n"
"font prochars\n"
"cursor ch5\n"
"weapon w_railgun.md2\n"
"style --compact --center --transparent\n"

"\n"
"color normal    #ffffffff\n"
"color selectable #ffffffff\n"
"color alternate #ffffffff\n"
"color title     #aa4651ff\n"
"color active     #3f6da0ff\n"
"color selection  #aa4651ff\n"
"color focus      #5a5f6666\n"
"color focus_border #b8bec8aa\n"
"color disabled   #aa4651ff\n"
"\n"
"begin main\n"

"    title \"Main Menu\"\n"
"\n"
"    action --status \"Find and join online games.\" \"multiplayer\" pushmenu multiplayer\n"
"    action --status \"Engine and gameplay configuration.\" \"options\" pushmenu options\n"
"    action --status \"Display and resolution settings.\" \"video setup\" pushmenu video\n"
"    blank\n"
"    action --status \"Exit the game.\" \"quit\" quit\n"
"end\n"
"\n"
"begin game\n"

"    title \"In-Game Menu\"\n"
"    action --status \"Match voting, teams, and server interaction.\" \"Join game\" pushmenu game_server\n"
"    blank\n"
"    action --status \"Configure HUD, speedometer, and strafe helper.\" \"HUD & Jump Tools\" pushmenu jump\n"
"    action --status \"Quickly tweak brightness and graphics.\" \"Quick Video Settings\" pushmenu video_quick\n"
"    action --status \"Engine, keyboard, and mouse options.\" \"System Options\" pushmenu options\n"
"    blank\n"
"    action --status \"Find active jump and race servers.\" \"Find Jump Servers\" pushmenu servers \"@jump +http://q2servers.com/?raw=2&mod=jump\"\n"
"    action --status \"Quick access to your saved servers.\" \"Address Book\" pushmenu servers \"favorites://\" \"file:///servers.lst\" \"broadcast://\"\n"
"    blank\n"
"    action --status \"Leave the current server.\" \"Disconnect\" disconnect\n"
"    action --status \"Exit the game.\" \"Quit Game\" quit\n"
"end\n"
"\n"

"begin game_server\n"

"    title \"=== Server Actions ===\"\n"
"    action --status \"Join the hard team.\" \"Join Team Hard\" team hard\n"
"    action --status \"Join the easy team.\" \"Join Team Easy\" team easy\n"
"    blank\n"
"    action --status \"Vote YES on the current call.\" \"Vote YES\" yes\n"
"    action --status \"Vote NO on the current call.\" \"Vote NO\" no\n"
"    action --status \"Call vote for extra map time.\" \"Vote More Time\" votetime 5\n"
"    action --status \"Call vote for a random map.\" \"Vote Random Map\" mapvote random\n"
"end\n"
"\n"

"begin options\n"
"    title \"Options\"\n"

"\n"
"    action --status \"Customize your player name and appearance.\" \"player setup\" pushmenu players\n"
"    action --status \"Configure jump-specific HUD and assist tools.\" \"jump setup\" pushmenu jump\n"
"    action --status \"Adjust mouse sensitivity and input settings.\" \"input setup\" pushmenu input\n"
"    action --status \"Bind movement and game actions to keys.\" \"key bindings\" pushmenu keys\n"
"    action --status \"Graphics, resolution, and quality settings.\" \"video setup\" pushmenu video\n"
"    action --status \"Audio levels and engine settings.\" \"sound setup\" pushmenu sound\n"
"    action --status \"Explosions, shadows, and rail trails.\" \"effects setup\" pushmenu effects\n"
"    action --status \"HUD size, opacity, and scaling.\" \"screen setup\" pushmenu screen\n"
"    action --status \"Menu scale, style, source, and cursor settings.\" \"menu setup\" pushmenu menusetup\n"
"    action --status \"Asset downloading preferences.\" \"download options\" pushmenu downloads\n"
"    action --status \"Quick-connect address book.\" \"address book\" pushmenu addressbook\n"
"end\n"
"\n"
"begin multiplayer\n"

"    title \"Multiplayer\"\n"
"\n"
"    action --status \"Browse all active Quake 2 servers.\" \"browse q2servers.com\" pushmenu servers \"+http://q2servers.com/?raw=2\"\n"
"    action --status \"Find active jump and race servers.\" \"browse jump servers\" pushmenu servers \"@jump +http://q2servers.com/?raw=2&mod=jump\"\n"
"    action --status \"Quick access to your saved servers.\" \"browse address book\" pushmenu servers \"favorites://\" \"file:///servers.lst\" \"broadcast://\"\n"
"    action --status \"Watch recorded match and jump replays.\" \"browse demos\" pushmenu demos\n"
"end\n"
"\n"
"begin video\n"
"    title \"Video Setup\"\n"
"\n"
"    style --live\n"
"    values --defer --show-value --status \"Switch between fullscreen and windowed modes.\" \"video mode\" vid_fullscreen windowed $$vid_modelist\n"
"    toggle --show-value --status  \"Use a borderless window. With fullscreen enabled, this becomes borderless fullscreen.\" \"borderless\" vid_noborder\n"
"    select --show-value --status  \"Adjust how Field of View is calculated for wide screens.\" \"fov scaling\" cl_adjustfov vert- hor+\n"
"    toggle --show-value --status  \"Synchronize frame rate with monitor refresh to prevent tearing.\" \"vertical sync\" gl_swapinterval\n"
"    pairs --defer --show-value --status \"Smooth jagged edges of geometry.\" \"anti-aliasing\" gl_multisamples no 0 \"2x MSAA\" 2 \"4x MSAA\" 4 \"8x MSAA\" 8\n"
"    range --defer --show-value --status \"Adjust the brightness balance of game textures.\" \"texture gamma\" vid_gamma 1.3 0.3\n"
"    toggle --defer --show-value --status \"Toggle use of monitor hardware for gamma correction.\" \"hardware gamma\" vid_hwgamma\n"
"    range --defer --show-value --status \"Lower values increase texture detail.\" \"texture quality\" gl_picmip 3 0 -1\n"
"    pairs --status \"Choose between classic pixelated or modern smooth textures.\" \"texture filter\" gl_texturemode \\\n"
"        nearest GL_NEAREST \\\n"
"        linear GL_LINEAR \\\n"
"        bilinear GL_LINEAR_MIPMAP_NEAREST \\\n"
"        trilinear GL_LINEAR_MIPMAP_LINEAR\n"
"    pairs --show-value --status \"Improve texture clarity on surfaces viewed at an angle.\" \"anisotropic filter\" gl_anisotropy no 1 2x 2 4x 4 8x 8 16x 16\n"
"    range --defer --show-value --status \"Adjust the color intensity of game world textures.\" \"texture saturation\" gl_saturation 0 1\n"
"    range --show-value --status \"Boost the overall brightness of textures.\" \"texture intensity\" intensity 1 3 0.1\n"
"    range --show-value --status \"Adjust the color intensity of static lightmaps.\" \"lightmap saturation\" gl_coloredlightmaps 0 1\n"
"    range --show-value --status \"Fine-tune the brightness of static lighting.\" \"lightmap brightness\" gl_brightness 0 0.3\n"
"    toggle --show-value --status \"Legacy GL1.x vs Modern GL3.x shaders.\" \"Shaders\" gl_shaders\n"
"    blank\n"
"    action --status \"Configure advanced and modern rendering options.\" --align \"advanced settings...\" pushmenu video_advanced\n"
"end\n"
"\n"
"begin video_advanced\n"

"    title \"Advanced Video\"\n"
"    style --live\n"
"\n"
"    toggle --status \"Draw skybox textures (disable to draw black sky).\" \"draw skybox\" gl_drawsky\n"
"    toggle --status \"Bilinear filtering of skybox textures.\" \"sky filtering\" gl_bilerp_skies\n"
"    pairs --defer --status \"HQ upscale filter for PCX images (improves scaled HUD elements).\" \"HUD image upscale\" gl_upscale_pcx no 0 2x 1 4x 2\n"
"    pairs --status \"Bilinear filtering level for HUD pictures.\" \"HUD image filter\" gl_bilerp_pics off 0 \"large only\" 1 all 2\n"
"    pairs --status \"Draw drop-shadow under text to improve readability.\" \"text shadow\" gl_fontshadow no 0 1px 1 2px 2\n"
"    toggle --status \"Bilinear filtering of console and menu text.\" \"text filtering\" gl_bilerp_chars\n"
"    pairs --defer --status \"Search for truecolor replacements (PNG/JPG/TGA) for game textures.\" \"texture override\" r_override_textures off 0 \"palettized only\" 1 all 2\n"
"    select --status \"File format used when taking screenshots.\" \"screenshot format\" gl_screenshot_format jpg png tga\n"
"    blank\n"
"end\n"
"\n"
"begin video_quick\n"

"    title \"Quick Video\"\n"
"\n"
"    style --live\n"
"    range --show-value --status \"Texture lightmap multiplier (higher values make world textures brighter).\" \"world modulation\" gl_modulate 1 20 0.5\n"
"    range --show-value --status \"Adjust the brightness of static lighting.\" \"lightmap brightness\" gl_brightness 0 1 0.1\n"
"    range --show-value --status \"Boost the overall brightness of textures.\" \"texture intensity\" intensity 1 5 0.1\n"
"    toggle --status \"Clear background when outside map.\" \"fix artifacts\" gl_clear\n"
"    toggle --status \"Fullbright.\" \"fullbright\" r_fullbright\n"
"    toggle --defer --status \"Override default .wal textures.\" \"Override textures\" r_override_testures\n"
"    action_select --show-value --status \"Change sky.\" \"sky\" sky black blue bluesky unit1_ strogg_moon_ space1 the_moon_ hub_ u6_\n"
"end\n"
"\n"

"begin sound\n"
"    title \"Sound Setup\"\n"

"\n"
"    values --status \"Select the audio output engine (OpenAL recommended).\" \"sound engine\" s_enable \"no sound\" \"software\" \"OpenAL\"\n"
"    range --show-value --status \"Lower values reduce delay but may cause stuttering.\" \"sound latency\" s_mixahead 0.05 0.2 --show-if s_enable !0\n"
"    range --show-value --status \"Overall volume of sound effects and voices.\" \"effects volume\" s_volume 0 1 --show-if s_enable !0\n"
"    range --show-value --status \"Volume level for background OGG music.\" \"music volume\" ogg_volume 0 1 --show-if ogg_enable !0\n"
"    toggle --status \"Enable or disable background music playback.\" \"enable music\" ogg_enable --show-if s_enable !0\n"
"    toggle --status \"Play music tracks in random order.\" \"shuffle tracks\" ogg_shuffle --show-if ogg_enable !0\n"
"    toggle --status \"Apply a muffled audio filter when submerged.\" \"underwater effect\" s_underwater --show-if s_enable !0\n"
"    values --status \"Ambient map sounds like wind or humming machinery.\" \"ambient sounds\" s_ambient \"no\" \"yes\" \"only player's own\" --show-if s_enable !0\n"
"    select --status \"Sound notification when receiving a chat message.\" \"chat beep\" cl_chat_sound \"disabled\" \"default\" \"alternative\" --show-if s_enable !0\n"
"    blank\n"
"    toggle --status \"Automatically mute sound when game window loses focus.\" \"mute when inactive\" s_auto_focus\n"
"    toggle --status \"Swap left and right audio channels.\" \"swap stereo channels\" s_swapstereo --show-if s_enable !0\n"
"    pairs --status \"Allow OpenAL Soft HRTF mixing for spatial 3D audio.\" \"spatial audio (HRTF)\" al_hrtf off 0 default 1 on 2 --show-if s_enable 2\n"
"end\n"
"\n"
"begin railtrail\n"
"    title \"Railgun Trail Setup\"\n"

"\n"
"    values --status \"Visual style of the railgun beam.\" \"rail trail type\" cl_railtrail_type \\\n"
"        \"default\" \"core only\" \"core and spiral\"\n"
"    range --show-value --status \"How long the trail remains visible in seconds.\" \"rail trail duration\" cl_railtrail_time 0.1 3.0 0.1\n"
"    range --show-value --status \"Thickness of the inner beam.\" \"core width\" cl_railcore_width 1 6 1\n"
"    range --show-value --status \"Spiral radius of the outer effect.\" \"spiral radius\" cl_railspiral_radius 1 6 1\n"
"    strings --status \"Color of the inner beam.\" \"core color\" cl_railcore_color \\\n"
"        black red green yellow blue cyan magenta white\n"
"    strings --status \"Color of the outer spiral.\" \"spiral color\" cl_railspiral_color \\\n"
"        black red green yellow blue cyan magenta white\n"
"end\n"
"\n"
"begin effects\n"
"    title \"Effects Setup\"\n"
"\n"
"    values --status \"World lighting from projectiles and explosions.\" \"dynamic lighting\" gl_dynamic \"no\" \"yes\" \"only switchable\"\n"
"    select --status \"Cartoon-style thick outlines on players and items.\" \"entity cel-shading\" gl_celshading no 1x 2x 3x\n"
"    toggle --status \"Enable glowing shell around certain entities.\" \"entity glowing\" cl_noglow ~\n"
"    select --status \"Drop-shadows under players and objects.\" \"ground shadows\" gl_shadows no yes fade\n"
"    toggle --status \"Screen tinting from items and environment (lava/water).\" \"screen blending\" gl_polyblend\n"
"    toggle --status \"Visual distortion effect when underwater.\" \"screen warping\" gl_waterwarp\n"
"    toggle --status \"Show or hide grenade explosion effects.\" \"grenade explosions\" cl_disable_explosions ~0\n"
"    toggle --status \"Show or hide rocket explosion effects.\" \"rocket explosions\" cl_disable_explosions ~1\n"
"    toggle --status \"Toggle dynamic lighting muzzle flashes.\" \"muzzle flashes\" cl_muzzleflashes\n"
"    toggle --status \"Toggle weapon muzzle flash flare effects.\" \"weapon flares\" cl_flares\n"
"    toggle --status \"Toggle rendering of body parts and blood splatters.\" \"blood and gibs\" cl_gibs\n"
"    toggle --status \"Disable rendering of all particle effects.\" \"disable particles\" cl_disable_particles\n"
"    toggle --status \"Toggle screen hit markers on successful shots.\" \"hit markers\" cl_hit_markers\n"
"    blank\n"
"    toggle --status \"Toggles gun model bobbing when moving.\" \"weapon bobbing\" cl_nobob ~\n"
"    range --show-value --status \"Transparency of the player gun model.\" \"weapon opacity\" cl_gunalpha 0 1\n"
"    range --show-value --status \"Field of view for the player weapon model (0 uses main FOV).\" \"weapon FOV\" cl_gunfov 0 120 5\n"
"    blank\n"
"    action --status \"Customize railgun beam colors and style.\" --align \"railgun trail setup...\" pushmenu railtrail\n"
"end\n"
"\n"
"begin crosshair\n"
"    title \"Crosshair Setup\"\n"

"\n"
"    select --status \"Style of the center-screen aiming cursor.\" \"crosshair type\" crosshair none cross dot angle\n"
"    pairs --status \"Change the physical size of the crosshair.\" \"crosshair scale\" ch_scale 0.5x 0.5 1x 1 2x 2 --show-if crosshair !0\n"
"    toggle --status \"Change crosshair color based on player health.\" \"color by health\" ch_health --show-if crosshair !0\n"
"    range --show-value --status \"Red intensity of the crosshair color.\" \"red channel\" ch_red 0 1 --show-if crosshair !0\n"
"    range --show-value --status \"Green intensity of the crosshair color.\" \"green channel\" ch_green 0 1 --show-if crosshair !0\n"
"    range --show-value --status \"Blue intensity of the crosshair color.\" \"blue channel\" ch_blue 0 1 --show-if crosshair !0\n"
"    range --show-value --status \"Opacity level of the crosshair.\" \"alpha channel\" ch_alpha 0 1 --show-if crosshair !0\n"
"end\n"
"\n"
"begin screen\n"
"    title \"Screen Setup\"\n"

"\n"
"    range --show-value --status \"Vertical field of view adjustment (legacy).\" \"screen size\" viewsize 40 100 10\n"
"    toggle --status \"Show a real-time graph of server latency.\" \"ping graph\" scr_lag_draw\n"
"    pairs --status \"Show a subtle network history indicator.\" \"network bar\" sh_netmeter off 0 lagometer 1 netgraph 2 histogram 3\n"
"    toggle --status \"Show short warnings for run-affecting network incidents.\" \"network notice\" sh_netalert\n"
"    select --status \"Detailed recording status bar for demos.\" \"demo bar\" scr_demobar no yes verbose\n"
"    pairs --show-value --status \"Text dump of frame/network errors.\" \"turtle text\" scr_showturtle off 0 normal 1 verbose 2\n"
"    range --show-value --status \"Overall transparency of the in-game HUD.\" \"HUD opacity\" scr_alpha 0 1\n"
"    range --show-value --status \"Transparency of the background console.\" \"console opacity\" con_alpha 0 1\n"
"    pairs --status \"Scale factor for all HUD elements.\" \"HUD scale\" scr_scale auto 0 1x 1 2x 2 4x 4\n"
"    pairs --status \"Scale factor for the console text.\" \"console scale\" con_scale auto 0 1x 1 2x 2 4x 4\n"
"    blank\n"
"    toggle --status \"Show digital clock in the console.\" \"console clock\" con_clock\n"
"    range --show-value --status \"Fraction of the screen height the console occupies.\" \"console height\" con_height 0.1 1.0\n"
"    blank\n"
"    action --status \"Adjust aiming cursor appearance.\" --align \"crosshair setup...\" pushmenu crosshair\n"
"    action --status \"Configure jump-specific assist tools.\" --align \"jump HUD setup...\" pushmenu jump\n"
"end\n"
"\n"
"begin menusetup\n"
"    title \"Menu Setup\"\n"
"\n"
"\n"
"    style --live\n"
"    pairs --status \"Scale factor for this menu system.\" \"menu scale\" ui_scale auto 0 1x 1 2x 2 4x 4\n"
"    action --status \"Adjust the menu palette.\" --align \"menu colors...\" pushmenu menu_colors\n"
"    select --status \"Focus highlight width style.\" \"focus width\" ui_menu_focus_width full content\n"
"    range --show-value --status \"Density of rows in menus.\" \"menu density\" ui_menu_density -4 10 1\n"
"\n"
"    range --show-value --status \"Horizontal padding inside the focus highlight bar.\" \"focus pad x\" ui_menu_focus_padding_x 0 50 1 --show-if ui_menu_focus_width !full\n"
"    range --show-value --status \"Vertical padding inside the focus highlight bar.\" \"focus pad y\" ui_menu_focus_padding_y 0 20 1 --show-if ui_menu_focus_width !full\n"
"    blank\n"
"    range --show-value --status \"Transparency of the menu background overlay image.\" \"bar overlay alpha\" ui_menu_bar_image_alpha 0 1\n"
"    strings --status \"Scaling mode for the menu background overlay image.\" \"bar overlay mode\" ui_menu_bar_image_mode cover contain screen stretch fill\n"
"    blank\n"
"    toggle --status \"Animate focus highlight transitions between menu items.\" \"focus animation\" ui_menu_anim\n"
"    range --show-value --status \"Duration in ms for the focus highlight animation.\" \"focus animation ms\" ui_menu_anim_focus_ms 0 500 10 --show-if ui_menu_anim !0\n"
"    blank\n"
"    select --status \"Change OS cursor style for windowed and borderless menus.\" \"system cursor\" win_menu_cursor arrow cross hand ibeam wait no size --show-if ui_borderless_or_windowed 1\n"
"    select --status \"Texture cursor used in exclusive fullscreen menus.\" \"menu cursor texture\" cl_menu_cursor none cross dot angle ch4 ch5 --show-if ui_exclusive_fullscreen 1\n"
"    pairs --status \"Choose the menu source used after the next UI restart. Built-in is available only when game is jump; other games load q2pro.menu.\" \"menu source\" ui_external_menu built-in 0 \"external file\" 1\n"
"    action --status \"Animated player model appearance and behavior.\" \"model setup\" pushmenu model\n"
"end\n"
"\n"
"begin menu_colors\n"
"    title \"Menu Colors\"\n"

"\n"
"    style --live\n"
"    blank\n"
"    field --picker --status \"Whole menu panel background.\" \"panel background\" ui_menu_color_panel_bg\n"
"    field --picker --status \"Panel outline border.\" \"panel border\" ui_menu_color_panel_border\n"
"    field --picker --status \"Panel drop shadow.\" \"panel shadow\" ui_menu_color_panel_shadow\n"
"    blank\n"
"    field --picker --status \"Top menu title text.\" \"title text\" ui_menu_color_title_text\n"
"    field --picker --status \"Default menu text.\" \"normal text\" ui_menu_color_text\n"
"    field --picker --status \"Left-side labels and secondary text.\" \"label text\" ui_menu_color_label_text\n"
"    field --picker --status \"Unavailable item text.\" \"disabled text\" ui_menu_color_disabled_text\n"
"    blank\n"
"    field --picker --status \"Unfocused selectable item text.\" \"item text\" ui_menu_color_item_text\n"
"    field --picker --status \"Text on the currently focused control.\" \"focused text\" ui_menu_color_focus_text\n"
"    field --picker --status \"Focused row background marker.\" \"focused row\" ui_menu_color_focus_bg\n"
"    field --picker --status \"Focused row side edge.\" \"focused row edge\" ui_menu_color_focus_edge\n"
"    field --picker --status \"Focused item triangle marker.\" \"focus marker\" ui_menu_color_focus_marker\n"
"    blank\n"
"    field --picker --status \"Value column/right-side text.\" \"value text\" ui_menu_color_value_text\n"
"    field --picker --status \"Focused value column text.\" \"active value text\" ui_menu_color_value_active_text\n"
"    field --picker --status \"Modified/unsaved value text.\" \"changed value text\" ui_menu_color_value_changed_text\n"
"    blank\n"
"    field --picker --status \"Slider background track.\" \"slider track\" ui_menu_color_slider_track\n"
"    field --picker --status \"Slider active progress fill.\" \"slider fill\" ui_menu_color_slider_fill\n"
"    field --picker --status \"Slider active thumb/knob.\" \"slider thumb\" ui_menu_color_slider_thumb\n"
"    field --picker --status \"Slider active thumb outline/border.\" \"slider border\" ui_menu_color_slider_border\n"
"    blank\n"
"    field --picker --status \"List column header background.\" \"list header\" ui_menu_color_list_header_bg\n"
"    field --picker --status \"Sorted list column header background.\" \"sorted list header\" ui_menu_color_sorted_header_bg\n"
"    field --picker --status \"Selected row background in lists.\" \"selected row\" ui_menu_color_selection_bg\n"
"    field --picker --status \"Scrollbar background track.\" \"scrollbar track\" ui_menu_color_scrollbar_track\n"
"    blank\n"
"    field --picker --status \"Tab text in server browser.\" \"tab text\" ui_menu_color_tab_text\n"
"    field --picker --status \"Active tab text in server browser.\" \"active tab text\" ui_menu_color_tab_active_text\n"
"    field --picker --status \"Active tab background box in server browser.\" \"active tab background\" ui_menu_color_tab_active_bg\n"
"    field --picker --status \"Inactive tab background box in server browser.\" \"inactive tab background\" ui_menu_color_tab_inactive_bg\n"
"    field --picker --status \"Line under active server browser tab.\" \"tab underline\" ui_menu_color_tab_underline\n"
"    blank\n"
"    field --picker --status \"Bottom hint bar background.\" \"hint background\" ui_menu_color_hint_bg\n"
"    field --picker --status \"Bottom hint bar text.\" \"hint text\" ui_menu_color_hint_text\n"
"    blank\n"
"    action --status \"Restore all menu colors to their default q2jump palette values.\" --align \"reset menu colors\" ui_reset_menu_colors\n"
"end\n"
"\n"
"begin downloads\n"
"    title \"Download Options\"\n"

"\n"
"    toggle --status \"Global switch for automated server downloads.\" \"allow downloading\" allow_download\n"
"    toggle --status \"Automatically fetch missing .bsp files.\" \"maps\" allow_download_maps --show-if allow_download !0\n"
"    toggle --status \"Fetch custom player models and skins.\" \"player models/skins\" allow_download_players --show-if allow_download !0\n"
"    toggle --status \"Fetch custom 3D map objects and entities.\" \"models\" allow_download_models --show-if allow_download !0\n"
"    toggle --status \"Fetch custom weapon and ambient sounds.\" \"sounds\" allow_download_sounds --show-if allow_download !0\n"
"    toggle --status \"Fetch high-res or custom world textures.\" \"textures\" allow_download_textures --show-if allow_download !0\n"
"    toggle --status \"Fetch custom images, banners, and logos.\" \"pics\" allow_download_pics --show-if allow_download !0\n"
"    blank --show-if allow_download !0\n"
"    toggle --status \"Use high-speed web downloads where available.\" \"HTTP downloads\" cl_http_downloads --show-if allow_download !0\n"
"end\n"
"\n"
"begin input\n"
"    title \"Input Setup\"\n"

"\n"
"    field --numeric --width 8 --status \"Multiplier for mouse movement speed.\" \"mouse sens\" sensitivity\n"
"    toggle --status \"Automatically scale sensitivity based on resolution.\" \"auto sens\" m_autosens\n"
"    toggle --status \"Smooth out erratic mouse movement.\" \"mouse filter\" m_filter\n"
"    toggle --status \"Use the mouse to aim around (recommended).\" \"free look\" freelook\n"
"    toggle --status \"Player always moves at running speed.\" \"always run\" cl_run\n"
"end\n"
"\n"
"begin keys\n"
"    title \"Key Bindings\"\n"
"\n"
"    bind --status \"Fire current weapon.\" \"attack\" +attack\n"
"    bind --status \"Move the player forward.\" \"walk forward\" +forward\n"
"    bind --status \"Move the player backward.\" \"backpedal\" +back\n"
"    bind --status \"Hold to walk or run (depending on settings).\" \"run\" +speed\n"
"    bind --status \"Side-step to the left.\" \"step left\" +moveleft\n"
"    bind --status \"Side-step to the right.\" \"step right\" +moveright\n"
"    bind --status \"Jump upward.\" \"up / jump\" +moveup\n"
"    bind --status \"Double-jump script (+dj).\" \"double jump\" +dj\n"
"    bind --status \"Crouch/duck\" \"down / crouch\" +movedown\n"
"    bind --status \"Open the items and equipment list.\" \"inventory\" inven\n"
"    bind --status \"Activate the currently selected item.\" \"use item\" invuse\n"
"    bind --status \"Discard the currently selected item.\" \"drop item\" invdrop\n"
"    bind --status \"Highlight previous inventory item.\" \"prev item\" invprev\n"
"    bind --status \"Highlight next inventory item.\" \"next item\" invnext\n"
"    bind --status \"Display current objective or help.\" \"help computer\" help\n"
"    bind --status \"Toggle the match statistics display.\" \"scoreboard\" score\n"
"    bind --status \"Open the global chat console.\" \"chat\" messagemode\n"
"    blank\n"
"    action --status \"Bindings for keyboard-only aiming and turning.\" --align \"legacy keys...\" pushmenu legacykeys\n"
"end\n"
"\n"
"begin legacykeys\n"
"    title \"Legacy Key Bindings\"\n"
"    background #3f6da040\n"
"\n"
"    bind --status \"Rotate view to the left (keyboard).\" \"turn left\" +left\n"
"    bind --status \"Rotate view to the right (keyboard).\" \"turn right\" +right\n"
"    bind --status \"Modifier for keyboard-driven strafing.\" \"sidestep\" +strafe\n"
"    bind --status \"Tilt view upward (keyboard).\" \"look up\" +lookup\n"
"    bind --status \"Tilt view downward (keyboard).\" \"look down\" +lookdown\n"
"    bind --status \"Snap view back to horizon level.\" \"center view\" centerview\n"
"    bind --status \"Enable mouse-driven aiming (legacy).\" \"mouse look\" +mlook\n"
"    bind --status \"Enable keyboard-driven aiming (legacy).\" \"keyboard look\" +klook\n"
"end\n"
"\n"
"begin addressbook\n"

"    title \"Address Book\"\n"
"    field --width 32 --center --status \"Favorite server address slot 0.\" adr0\n"
"    field --width 32 --center --status \"Favorite server address slot 1.\" adr1\n"
"    field --width 32 --center --status \"Favorite server address slot 2.\" adr2\n"
"    field --width 32 --center --status \"Favorite server address slot 3.\" adr3\n"
"    field --width 32 --center --status \"Favorite server address slot 4.\" adr4\n"
"    field --width 32 --center --status \"Favorite server address slot 5.\" adr5\n"
"    field --width 32 --center --status \"Favorite server address slot 6.\" adr6\n"
"    field --width 32 --center --status \"Favorite server address slot 7.\" adr7\n"
"    field --width 32 --center --status \"Favorite server address slot 8.\" adr8\n"
"    field --width 32 --center --status \"Favorite server address slot 9.\" adr9\n"
"    field --width 32 --center --status \"Favorite server address slot 10.\" adr10\n"
"    field --width 32 --center --status \"Favorite server address slot 11.\" adr11\n"
"    field --width 32 --center --status \"Favorite server address slot 12.\" adr12\n"
"    field --width 32 --center --status \"Favorite server address slot 13.\" adr13\n"
"    field --width 32 --center --status \"Favorite server address slot 14.\" adr14\n"
"    field --width 32 --center --status \"Favorite server address slot 15.\" adr15\n"
"end\n"
"\n"
"begin jump\n"

"    title \"Jump Setup\"\n"
"\n"
"    style --live\n"
"    blank\n"
"    action --status \"Configure the visual strafe-assist bar.\" \"Strafe Helper\" pushmenu strafehelper\n"
"    action --status \"Show your current speed (Units Per Second).\" \"UPS display\" pushmenu jumpups\n"
"    action --status \"Draw a trailing line behind your movement.\" \"Race line\" pushmenu raceline\n"
"    action --status \"Configure subtle network history indicator.\" \"Network Bar\" pushmenu jumpnetwork\n"
"    action --status \"Configure on-screen network warning alerts.\" \"Network Alerts\" pushmenu jumpnetalerts\n"
"    action --status \"Bind keys for movement.\" \"Core Bindings\" pushmenu corebindings\n"
"    action --status \"Bind keys for mod-specific actions.\" \"Mod Bindings\" pushmenu jumpmodbinds\n"
"    action --status \"Bind FPS preset keys and hold-to-change FPS keys.\" \"FPS Setup\" pushmenu jumpfpssetup\n"
"    blank\n"
"    action --status \"Technical settings and debug commands.\" \"advanced/debug\" pushmenu jumpdebug\n"
"end\n"
"\n"
"begin corebindings\n"

"    title \"Core Bindings\"\n"
"\n"
"    bind --status \"Move player forward (+forward).\" \"walk forward\" +forward\n"
"    bind --status \"Move player backward (+back).\" \"backpedal\" +back\n"
"    bind --status \"Side-step to the left (+moveleft).\" \"strafe left\" +moveleft\n"
"    bind --status \"Side-step to the right (+moveright).\" \"strafe right\" +moveright\n"
"    blank\n"
"    bind --status \"The primary jump action (+moveup).\" \"jump\" +moveup\n"
"    bind --status \"Double-jump script (+dj).\" \"double jump\" +dj\n"
"    bind --status \"Move downward or crouch (+movedown).\" \"crouch\" +movedown\n"
"    blank\n"
"    bind --status \"Open q2jump menu.\" \"Menu\" inven\n"
"    bind --status \"Activate the currently selected item.\" \"Select\" invuse\n"
"    bind --status \"Highlight previous.\" \"prev item\" invprev\n"
"    bind --status \"Highlight next.\" \"next item\" invnext\n"
"    bind --status \"Open scoreboard.\" \"scoreboard\" score\n"
"    blank\n"
"end\n"
"\n"
"begin jumpmodbinds\n"

"    title \"Mod Bindings\"\n"
"\n"
"    bind --status \"Joins the Easy team (practice).\" \"join easy\" \"team easy\"\n"
"    bind --status \"Joins the Hard team (setting time).\" \"join hard\" \"team hard\"\n"
"    bind --status \"Respawn.\" \"kill\" kill\n"
"\n"
"    bind --status \"Saves current position.\" \"store\" store\n"
"    bind --status \"Toggle velocity in store.\" \"velstore\" velstore\n"
"    bind --status \"Returns to your stored position.\" \"recall\" recall\n"
"    bind --status \"Resets store position.\" \"reset\" reset\n"
"    bind --status \"noclip.\" \"noclip\" noclip\n"
"    blank\n"
"\n"
"    bind --status \"Draw a marker at map coordinate 0 0 0.\" \"world origin\" cl_drawworldorigin\n"
"    bind --status \"Toggles the replay statistics display.\" \"replay stats\" repstats\n"
"    bind --status \"Toggles jump distance announcement.\" \"show jumps\" showjumps\n"
"    bind --status \"Toggles other players time print.\" \"show times\" showtimes\n"
"    bind --status \"Toggles checkpoint sound.\" \"checkpoint sound\" cpsound\n"
"    bind --status \"Shows actual FPS.\" \"show FPS\" !fps\n"
"    blank\n"
"\n"
"    bind --status \"Votes YES in current election.\" \"vote yes\" yes\n"
"    bind --status \"Votes NO in current election.\" \"vote no\" no\n"
"    bind --status \"Toggles your idle/AFK state.\" \"idle mode\" idle\n"
"    bind --status \"Moves you to the observer team.\" \"spectate\" observer\n"
"end\n"
"\n"
"begin jumpfpssetup\n"

"    title \"FPS Setup\"\n"
"\n"
"    action --status \"Bind keys to instant FPS presets (f20, f31, f60, f120...).\"\"FPS Bindings\" pushmenu jumpfpsbinds\n"
"    action --status \"Bind keys that lower FPS while held, restore when released.\"\"Hold FPS Binds\" pushmenu jumpholdfps\n"
"end\n"
"\n"
"begin jumpfpsbinds\n"

"    title \"FPS Bindings\"\n"
"\n"

"    bind --status \"Set cl_maxfps to 20\" \"FPS 20\" f20\n"
"    bind --status \"Set cl_maxfps to 22\" \"FPS 22\" f22\n"
"    bind --status \"Set cl_maxfps to 25\" \"FPS 25\" f25\n"
"    bind --status \"Set cl_maxfps to 26\" \"FPS 26\" f26\n"
"    bind --status \"Set cl_maxfps to 31\" \"FPS 31\" f31\n"
"    bind --status \"Set cl_maxfps to 32\" \"FPS 32\" f32\n"
"    bind --status \"Set cl_maxfps to 33\" \"FPS 33\" f33\n"
"    bind --status \"Set cl_maxfps to 60\" \"FPS 60\" f60\n"
"    bind --status \"Set cl_maxfps to 66\" \"FPS 66\" f66\n"
"    bind --status \"Set cl_maxfps to 90\" \"FPS 90\" f90\n"
"    bind --status \"Set cl_maxfps to 100\" \"FPS 100\" f100\n"
"    bind --status \"Set cl_maxfps to 120\" \"FPS 120\" f120\n"
"    blank\n"
"    action --status \"Back to FPS Setup.\" --align \"FPS Setup...\" pushmenu jumpfpssetup\n"
"end\n"
"\n"
"begin jumpholdfps\n"

"    title \"Hold FPS Binds\"\n"
"    style --live\n"
"\n"
"    blank\n"
"    bindselect2 \"1\" \"+fps_hold 1\" fps_hold_1 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_1 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"2\" \"+fps_hold 2\" fps_hold_2 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_2 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"3\" \"+fps_hold 3\" fps_hold_3 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_3 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"4\" \"+fps_hold 4\" fps_hold_4 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_4 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"5\" \"+fps_hold 5\" fps_hold_5 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_5 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"6\" \"+fps_hold 6\" fps_hold_6 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_6 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"7\" \"+fps_hold 7\" fps_hold_7 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_7 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"8\" \"+fps_hold 8\" fps_hold_8 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_8 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"9\" \"+fps_hold 9\" fps_hold_9 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_9 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"10\" \"+fps_hold 10\" fps_hold_10 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_10 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"11\" \"+fps_hold 11\" fps_hold_11 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_11 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    bindselect2 \"12\" \"+fps_hold 12\" fps_hold_12 20 22 25 26 30 31 32 33 60 66 90 100 120 : fps_release_12 20 22 25 26 30 31 32 33 60 66 90 100 120\n"
"    blank\n"
"    action --status \"Back to FPS Setup.\" --align \"FPS Setup...\" pushmenu jumpfpssetup\n"
"end\n"
"\n"
"begin strafehelper\n"
"    title \"Strafe Helper\"\n"
"\n"
"    style --live\n"
"    toggle --show-value --status \"Global switch for the strafe helper HUD element.\" \"enabled\" sh_draw\n"
"    toggle --show-value --status \"Show a central mark for neutral mouse position.\" \"center marker\" sh_centermarker --show-if sh_draw !0\n"
"    range --show-value --status \"Scale factor for the strafe helper bar.\" \"scale\" sh_scale 0.5 4.0 0.1 --show-if sh_draw !0\n"
"    range --show-value --status \"Vertical position from the top of the screen.\" \"Y position\" sh_y 0 320 5 --show-if sh_draw !0\n"
"    range --show-value --status \"Height of the strafe helper bar in pixels.\" \"height\" sh_height 4 80 1 --show-if sh_draw !0\n"
"    range --show-value --status \"Transparency of the strafe helper bar.\" \"alpha\" sh_alpha 0 1 0.05 --show-if sh_draw !0\n"
"    select --show-value --status \"Visual drawing style of the strafe helper.\" \"bar style\" sh_bar_style gradient solid outline minimal --show-if sh_draw !0\n"
"    range --show-value --status \"Smooth visual movement of strafe helper angles; 0 disables it.\" \"smoothing\" sh_smoothing 0 10 0.1 --show-if sh_draw !0\n"
"    pairs --show-value --status \"Easing curve used by strafe helper smoothing.\" \"   smoothing mode\" sh_smoothing_mode linear 1 quadratic 2 cubic 3 sine 4 exponential 5 --show-if sh_draw !0\n"
"    range --show-value --status \"Width of the center mouse position marker.\" \"center width\" sh_center_width 0.1 5 0.1 --show-if sh_draw !0\n"
"    range --show-value --status \"Width of the optimal acceleration zone.\" \"optimal width\" sh_optimal_width 0.1 5 0.1 --show-if sh_draw !0\n"
"    toggle --show-value --status \"Draw the optimal angle marker as an outline.\" \"optimal outline\" sh_optimal_outline --show-if sh_draw !0\n"
"    field --picker --status \"Color when mouse is within optimal zone.\" \"accelerating color\" sh_color_accelerating --show-if sh_draw !0\n"
"    field --picker --status \"Color when moving at perfect angle.\" \"optimal color\" sh_color_optimal --show-if sh_draw !0\n"
"    field --picker --status \"Color of the center neutral marker.\" \"center marker color\" sh_color_centermarker --show-if sh_draw !0\n"
"    blank --show-if sh_draw !0\n"
"    action --status \"Choose from a set of pre-defined color schemes.\" --align \"apply color preset...\" pushmenu shpresets --show-if sh_draw !0\n"
"end\n"
"\n"
"begin shpresets\n"

"    title \"Strafe Helper Presets\"\n"
"\n"
"    action --status \"Apply a randomized color scheme.\" --align \"random\" \"sh hud preset random\"\n"
"    action --status \"Original grey and blue theme.\" --align \"vanilla\" \"sh hud preset vanilla\"\n"
"    action --status \"Rich gold with deep blue contrasts.\" --align \"gold\" \"sh hud preset gold\"\n"
"    action --status \"Vivid RGB rainbow colors.\" --align \"rainbow\" \"sh hud preset rainbow\"\n"
"    action --status \"Magenta, cyan, and yellow overload.\" --align \"fever dream\" \"sh hud preset feverdream\"\n"
"    action --status \"Bold magenta and purple on black.\" --align \"nightmare\" \"sh hud preset nightmare\"\n"
"    action --status \"Calm blue and teal tones.\" --align \"ocean\" \"sh hud preset ocean\"\n"
"    action --status \"Classic CRT orange and green.\" --align \"retro\" \"sh hud preset retro\"\n"
"    action --status \"Warm amber tones with subtle highlights.\" --align \"amber\" \"sh hud preset amber\"\n"
"    action --status \"Cool sky blue with contrasting pink highlights.\" --align \"sky blue\" \"sh hud preset skyblue\"\n"
"    action --status \"Bright pinks with yellow.\" --align \"candy\" \"sh hud preset candy\"\n"
"    action --status \"Neon pink and cyan aesthetic.\" --align \"cyberpunk\" \"sh hud preset cyberpunk\"\n"
"    action --status \"Yellow, cyan, and magenta.\" --align \"party\" \"sh hud preset party\"\n"
"    action --status \"Golden wattle yellow, green, and white.\" --align \"aussie\" \"sh hud preset aussie\"\n"
"    action --status \"Bright green with muted gray and magenta.\" --align \"pepega\" \"sh hud preset pepega\"\n"
"    action --status \"Toxic green with magenta and black.\" --align \"toxic\" \"sh hud preset toxic\"\n"
"    action --status \"Black, white, and cyan blocks.\" --align \"pixelated\" \"sh hud preset pixelated\"\n"
"    action --status \"Earthy green tones.\" --align \"forest\" \"sh hud preset forest\"\n"
"    action --status \"Neon green, dark green, and magenta.\" --align \"radioactive\" \"sh hud preset radioactive\"\n"
"    action --status \"Warm coral tones with vivid blue accents.\" --align \"coral\" \"sh hud preset coral\"\n"
"    action --status \"Magenta, lime green, and orange.\" --align \"funky\" \"sh hud preset funky\"\n"
"    action --status \"Blue, yellow, and magenta sparks.\" --align \"electric\" \"sh hud preset electric\"\n"
"    action --status \"Bold red, green, and blue for maximum contrast.\" --align \"hudslut\" \"sh hud preset hudslut\"\n"
"    action --status \"Muted sandy tones with soft highlights.\" --align \"sand\" \"sh hud preset sand\"\n"
"    action --status \"Fiery red and orange with a yellow highlight.\" --align \"fire\" \"sh hud preset fire\"\n"
"    action --status \"Fresh green and white theme.\" --align \"mint\" \"sh hud preset mint\"\n"
"    action --status \"Magenta, bright white, and black.\" --align \"karen\" \"sh hud preset karen\"\n"
"    action --status \"Toxic green, yellow, and red explosion.\" --align \"nuclear\" \"sh hud preset nuclear\"\n"
"    action --status \"Neon yellow, magenta, and cyan.\" --align \"highlighter\" \"sh hud preset highlighter\"\n"
"    action --status \"Dark black, spooky magenta, and haunting white.\" --align \"cursed\" \"sh hud preset cursed\"\n"
"    action --status \"Black, white, and gray.\" --align \"zebra\" \"sh hud preset zebra\"\n"
"    action --status \"Cool icy cyan and white.\" --align \"ice\" \"sh hud preset ice\"\n"
"    action --status \"Transparent debugging preset.\" --align \"imposs\" \"sh hud preset imposs\"\n"
"    action --status \"Red, blue, and yellow for a playful feel.\" --align \"clown\" \"sh hud preset clown\"\n"
"    action --status \"Acidic green and yellow with teal.\" --align \"acid\" \"sh hud preset acid\"\n"
"    action --status \"Deep cherry red with soft pink accents.\" --align \"cherry\" \"sh hud preset cherry\"\n"
"    action --status \"Black, neon green, and blood red.\" --align \"venom\" \"sh hud preset venom\"\n"
"    action --status \"Red, yellow, and blue for mind-bending contrast.\" --align \"psycho\" \"sh hud preset psycho\"\n"
"    action --status \"Golden yellow, sky blue, and hot pink.\" --align \"doge\" \"sh hud preset doge\"\n"
"    action --status \"Hot orange and red theme.\" --align \"lava\" \"sh hud preset lava\"\n"
"    action --status \"Orange, pink, and green madness.\" --align \"toxic sunset\" \"sh hud preset toxicsunset\"\n"
"    action --status \"Subtle dark and grey tones.\" --align \"shadow\" \"sh hud preset shadow\"\n"
"    action --status \"Soft lavender tones with bright green.\" --align \"lavender\" \"sh hud preset lavender\"\n"
"    action --status \"Lush emerald green with light highlights.\" --align \"emerald\" \"sh hud preset emerald\"\n"
"    action --status \"List all available presets in the console.\" --align \"show all presets\" \"sh hud preset\"\n"
"end\n"
"\n"
"begin jumpups\n"

"    title \"UPS Display\"\n"
"\n"
"    style --live\n"
"    toggle --show-value --status \"Show current movement speed (Units Per Second).\" \"enabled\" sh_ups\n"
"    range --show-value --status \"Scale factor for the speed digits.\" \"scale\" sh_ups_scale 0.25 4 0.25 --show-if sh_ups !0\n"
"    range --show-value --status \"Vertical offset from screen center.\" \"Y position\" sh_ups_y -300 300 5 --show-if sh_ups !0\n"
"    toggle --show-value --status \"Draw a drop-shadow behind the speed digits.\" \"shadow\" sh_ups_shadow --show-if sh_ups !0\n"
"    toggle --show-value --status \"Hide the display when speed is zero.\" \"hide zero\" sh_ups_hide_zero --show-if sh_ups !0\n"
"    toggle --show-value --status \"Include vertical velocity component in calculations.\" \"3D speed\" sh_ups_3d --show-if sh_ups !0\n"
"    strings --show-value --status \"How speed changes affect text color.\" \"color mode\" sh_ups_color_mode dynamic static threshold rainbow gradient strafing --show-if sh_ups !0\n"
"    strings --show-value --status \"Display speed as raw number or with label.\" \"format\" sh_ups_format plain suffix prefix --show-if sh_ups !0\n"
"    field --picker --status \"Color used when gaining speed.\" \"gain color\" sh_ups_color_gain --show-if sh_ups !0\n"
"    field --picker --status \"Color used when losing speed.\" \"loss color\" sh_ups_color_loss --show-if sh_ups !0\n"
"    field --picker --status \"Color used when at constant speed.\" \"neutral color\" sh_ups_color_neutral --show-if sh_ups !0\n"
"end\n"
"\n"
"begin raceline\n"

"    title \"Race Line\"\n"
"\n"
"    style --live\n"
"    range --show-value --status \"Thickness of the movement trail line.\" \"width\" race_width 0 20 1\n"
"    range --show-value --status \"Opacity level of the movement trail.\" \"opacity\" race_alpha 0 1 0.05\n"
"    range --show-value --status \"Duration before the line fades away (ms).\" \"lifetime (ms)\" race_life 0 5000 100\n"
"    field --picker --status \"Color of the movement trail line.\" \"line color\" race_color\n"
"end\n"
"\n"
"begin jumpnetwork\n"

"    title \"Jump Network\"\n"
"\n"
"    style --live\n"
"    static \"[Run Feedback]\"\n"
"    pairs --show-value --status \"Localized network status indicator.\" \"network bar\" sh_netmeter off 0 lagometer 1 netgraph 2 histogram 3\n"
"    pairs --show-value --status \"Scale netmeter dynamically based on recent latency baseline.\" \"adaptive scaling\" sh_netmeter_adaptive off 0 on 1 --show-if sh_netmeter !0\n"
"    range --show-value --status \"Minimum latency scaling threshold in milliseconds.\" \"min latency\" sh_netmeter_min_ms 0 1000 10 --show-if sh_netmeter_adaptive 1\n"
"    range --show-value --status \"Maximum latency scaling threshold in milliseconds.\" \"max latency\" sh_netmeter_max_ms 0 1000 10 --show-if sh_netmeter_adaptive 1\n"
"    blank --show-if sh_netmeter !0\n"
"    static \"[Lagometer Layout]\" --show-if sh_netmeter 1\n"
"    range --show-value --status \"Horizontal offset; negative values align from the right edge.\" \"X position\" sh_lagometer_x -640 640 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Vertical offset; negative values align from the bottom edge.\" \"Y position\" sh_lagometer_y -480 480 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Opacity of normal samples; lower values keep stable network almost invisible.\" \"normal alpha\" sh_lagometer_alpha 0 1 0.05 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Opacity of loss/stall/prediction samples.\" \"incident alpha\" sh_lagometer_bad_alpha 0 1 0.05 --show-if sh_netmeter 1\n"
"    blank --show-if sh_netmeter 1\n"
"    static \"[Lagometer Theme & Colors]\" --show-if sh_netmeter 1\n"
"    range --show-value --status \"Normal packet color palette index.\" \"normal color\" sh_lagometer_color_normal 0 255 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Ping spike color palette index.\" \"spike color\" sh_lagometer_color_spike 0 255 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Ping jitter color palette index.\" \"jitter color\" sh_lagometer_color_jitter 0 255 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Incoming (Server-to-Client) packet loss color palette index.\" \"S2C loss color\" sh_lagometer_color_loss_s2c 0 255 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Outgoing (Client-to-Server) packet loss color palette index.\" \"C2S loss color\" sh_lagometer_color_loss_c2s 0 255 1 --show-if sh_netmeter 1\n"
"    blank --show-if sh_netmeter 1\n"
"    static \"[Netgraph Layout]\" --show-if sh_netmeter 2\n"
"    range --show-value --status \"Bar height in HUD pixels.\" \"height\" sh_netgraph_height 1 120 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Vertical offset; negative values align from the bottom edge.\" \"Y position\" sh_netgraph_y -480 480 1 --show-if sh_netmeter 2\n"
"    blank --show-if sh_netmeter 2\n"
"    static \"[Netgraph Theme & Colors]\" --show-if sh_netmeter 2\n"
"    range --show-value --status \"Normal packet color palette index.\" \"normal color\" sh_netgraph_color_normal 0 255 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Ping spike color palette index.\" \"spike color\" sh_netgraph_color_spike 0 255 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Ping jitter color palette index.\" \"jitter color\" sh_netgraph_color_jitter 0 255 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Incoming (Server-to-Client) packet loss color palette index.\" \"S2C loss color\" sh_netgraph_color_loss_s2c 0 255 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Outgoing (Client-to-Server) packet loss color palette index.\" \"C2S loss color\" sh_netgraph_color_loss_c2s 0 255 1 --show-if sh_netmeter 2\n"
"    blank --show-if sh_netmeter 2\n"
"    static \"[Histogram Layout]\" --show-if sh_netmeter 3\n"
"    range --show-value --status \"Bar height in HUD pixels.\" \"height\" sh_histogram_height 1 120 1 --show-if sh_netmeter 3\n"
"    pairs --show-value --status \"Choose full screen, half screen, or a custom histogram width.\" \"width\" sh_histogram_width_mode full 2 half 1 custom 0 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Custom bar width in HUD pixels; values beyond the current HUD width fill the screen.\" \"custom width\" sh_histogram_width 10 8192 10 --show-if ui_histogram_custom_width 1\n"
"    pairs --show-value --status \"Draw separated bars or fill each sample to the next one.\" \"fill mode\" sh_histogram_fill_mode bars 0 spans 1 --show-if sh_netmeter 3\n"
"    pairs --show-value --status \"Place samples by actual time or spread recent samples evenly across the bar.\" \"spacing\" sh_histogram_spacing_mode time 0 even 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Horizontal offset; negative values align from the right edge.\" \"X position\" sh_histogram_x -640 640 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Vertical offset; negative values align from the bottom edge.\" \"Y position\" sh_histogram_y -480 480 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Opacity of normal samples; lower values keep stable network almost invisible.\" \"normal alpha\" sh_histogram_alpha 0 1 0.05 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Opacity of loss/stall/prediction samples.\" \"incident alpha\" sh_histogram_bad_alpha 0 1 0.05 --show-if sh_netmeter 3\n"
"    range --show-value --status \"How much recent history the bar represents, in milliseconds.\" \"history ms\" sh_histogram_history_ms 500 120000 1000 --show-if sh_netmeter 3\n"
"    toggle --show-value --status \"Draw smoothed ping value over the histogram.\" \"ping display\" sh_histogram_ping --show-if sh_netmeter 3\n"
"    blank --show-if sh_netmeter 3\n"
"    static \"[Histogram Theme & Colors]\" --show-if sh_netmeter 3\n"
"    range --show-value --status \"Histogram background opacity level.\" \"background alpha\" sh_histogram_bg_alpha 0 1 0.05 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Histogram background color palette index.\" \"background color\" sh_histogram_color_bg 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Normal packet color palette index.\" \"normal color\" sh_histogram_color_normal 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Ping spike color palette index.\" \"spike color\" sh_histogram_color_spike 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Ping jitter color palette index.\" \"jitter color\" sh_histogram_color_jitter 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Incoming (Server-to-Client) packet loss color palette index.\" \"S2C loss color\" sh_histogram_color_loss_s2c 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Outgoing (Client-to-Server) packet loss color palette index.\" \"C2S loss color\" sh_histogram_color_loss_c2s 0 255 1 --show-if sh_netmeter 3\n"
"    blank --show-if sh_netmeter 3\n"
"    action --status \"Restore network bar, alert, and threshold settings to defaults.\" --align \"reset network defaults\" ui_reset_netmeter_settings\n"
"    blank\n"
"    action --status \"Configure latency and loss warning thresholds.\" \"threshold settings\" pushmenu jumpnetthresholds\n"
"end\n"
"\n"
"begin jumpnetalerts\n"

"    title \"Network Alerts\"\n"
"\n"
"    style --live\n"
"    static \"[Notice Feedback]\"\n"
"    toggle --show-value --status \"Short warning text for incidents likely to affect a run.\" \"incident notice\" sh_netalert\n"
"    blank --show-if sh_netalert !0\n"
"    static \"[Notice Layout]\" --show-if sh_netalert !0\n"
"    range --show-value --status \"Incident notice horizontal offset.\" \"notice X\" sh_netalert_x -640 640 1 --show-if sh_netalert !0\n"
"    range --show-value --status \"Incident notice vertical offset; negative values align from the bottom edge.\" \"notice Y\" sh_netalert_y -480 480 1 --show-if sh_netalert !0\n"
"    range --show-value --status \"Alert text color code (1=red, 2=green, 3=yellow, 4=blue, 5=cyan, 6=magenta, 7=severity-based, 8=orange, 9=purple).\" \"notice color\" sh_netalert_color 1 9 1 --show-if sh_netalert !0\n"
"    range --show-value --status \"How long incident text stays visible, in milliseconds.\" \"notice ms\" sh_netalert_duration_ms 250 5000 250 --show-if sh_netalert !0\n"
"    range --show-value --status \"Opacity of incident notice text.\" \"notice alpha\" sh_netalert_alpha 0 1 0.05 --show-if sh_netalert !0\n"
"    blank --show-if sh_netalert !0\n"
"    static \"[Notice Types]\" --show-if sh_netalert !0\n"
"    toggle --show-value --status \"Show notice for dropped packets.\" \"loss notice\" sh_netalert_loss --show-if sh_netalert !0\n"
"    toggle --show-value --status \"Show notice for repeated ping wobble.\" \"jitter notice\" sh_netalert_jitter --show-if sh_netalert !0\n"
"    toggle --show-value --status \"Show notice for sudden ping jumps.\" \"spike notice\" sh_netalert_spike --show-if sh_netalert !0\n"
"    blank --show-if sh_netalert !0\n"
"    action --status \"Configure latency and loss warning thresholds.\" \"threshold settings\" pushmenu jumpnetthresholds --show-if sh_netalert !0\n"
"    blank --show-if sh_netalert !0\n"
"    action --status \"Restore network bar, alert, and threshold settings to defaults.\" --align \"reset network defaults\" ui_reset_netmeter_settings\n"
"end\n"
"\n"
"begin jumpnetthresholds\n"

"    title \"Network Thresholds\"\n"
"\n"
"    style --live\n"
"    static \"[Latency Thresholds]\"\n"
"    toggle --show-value --status \"Compare spikes and jitter against your current ping baseline; recommended for distant servers.\" \"adaptive ping\" sh_netwarn_ping_adaptive\n"
"    range --show-value --status \"Minimum sudden ping jump before a spike warning.\" \"spike ms\" sh_netwarn_spike_ms 0 300 5 --show-if sh_netwarn_ping_adaptive 0\n"
"    range --show-value --status \"Adaptive spike threshold as percent of your rolling ping baseline.\" \"spike pct\" sh_netwarn_spike_pct 0 100 5 --show-if sh_netwarn_ping_adaptive 1\n"
"    range --show-value --status \"Repeated ping wobble threshold before jitter warning.\" \"jitter ms\" sh_netwarn_jitter_ms 0 150 5\n"
"    blank\n"
"    action --status \"Restore network bar, alert, and threshold settings to defaults.\" --align \"reset network defaults\" ui_reset_netmeter_settings\n"
"end\n"
"\n"
"begin model\n"
"\n"
"    title \"Model Setup\"\n"
"\n"
"    style --live\n"
"    toggle --status \"Draw an animated player model behind top-level menus.\" \"background model\" ui_menu_model\n"
"    blank\n"
"    select --status \"Preset position for the model on screen.\" \"position\" ui_menu_model_position custom center top bottom left right top-left top-right bottom-left bottom-right --show-if ui_menu_model !0\n"
"    range --show-value --status \"Horizontal position of the model (0=left, 1=right).\" \"model x\" ui_menu_model_x 0 1 --show-if ui_menu_model_position custom\n"
"    range --show-value --status \"Vertical position of the model (0=top, 1=bottom).\" \"model y\" ui_menu_model_y 0 1 --show-if ui_menu_model_position custom\n"
"    blank\n"
"    range --show-value --status \"Size of the animated menu background model.\" \"model scale\" ui_menu_model_scale 0.25 1.75 0.05 --show-if ui_menu_model !0\n"
"    range --show-value --status \"Facing angle of the animated menu background model.\" \"model yaw\" ui_menu_model_yaw 0 360 5 --show-if ui_menu_model !0\n"
"    range --show-value --status \"Camera distance from the model.\" \"model distance\" ui_menu_model_distance 32 160 1 --show-if ui_menu_model !0\n"
"    blank\n"
"    toggle --status \"Orbit the model by moving your mouse across its viewport.\" \"mouse orbit\" ui_menu_model_orbit --show-if ui_menu_model !0\n"
"end\n"
"\n"
"begin jumpdebug\n"

"    title \"Jump Debug\"\n"
"\n"
"    style --live\n"
"    pairs --status \"Smooth stair-step camera transitions (visual only, no physics advantage).\" \"step smooth\" cl_step_smoothing_mode q2pro q2pro r1q2-1 r1q2-1 r1q2-2 r1q2-2 r1q2-3 r1q2-3\n"
"    pairs --status \"Diagnostic overlay for movement physics.\" \"NerdStats\" sh_nerdstats off 0 left 1 right 2\n"
"    range --show-value --status \"World origin marker size in map units.\" \"origin size\" cl_worldorigin_size 0 16384 256 --show-if cl_drawworldorigin !0\n"
"    range --show-value --status \"World origin marker line width.\" \"origin line\" cl_worldorigin_linewidth 1 16 1 --show-if cl_drawworldorigin !0\n"
"    blank\n"
"    action --status \"Report current strafe helper internal state.\" --align \"show strafe helper status\" \"sh status\"\n"
"    action --status \"List all active jump-mod commands.\" --align \"show commands\" !help\n"
"    bind --status  \"debug physic.\" --align \"dump physics now\" debugnow\n"
"end\n"
;
