const char *ui_builtin_menu = 
"background #3f6da070\n"
"font prochars\n"
"cursor ch5\n"
"weapon w_railgun.md2\n"
"\n"

"color normal    #ffffffff\n"
"color selectable #ffffffff\n"
"color alternate #ffffffff\n"
"color title     #aa4651ff\n"
"color active     #3f6da0ff\n"
"color selection  #aa4651ff\n"
"color disabled   #aa4651ff\n"
"\n"
"begin video\n"
"    title \"Video Setup\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    values --show-value --status \"Switch between fullscreen and windowed modes.\" \"video mode\" vid_fullscreen windowed $$vid_modelist\n"
"    toggle --show-value --status \"Keep fullscreen visible and release the mouse while console is open on multi-monitor setups.\" \"multi-monitor\" vid_fullscreen_multimonitor --show-if vid_fullscreen !windowed\n"
"    values --show-value --status \"Adjust how Field of View is calculated for wide screens.\" \"fov scaling\" cl_adjustfov vert- hor+\n"
"    toggle --show-value --status \"Synchronize frame rate with monitor refresh to prevent tearing.\" \"vertical sync\" gl_swapinterval\n"
"    pairs --show-value --status \"Smooth jagged edges of geometry (requires video restart).\" \"anti-aliasing\" gl_multisamples no 0 \"2x MSAA\" 2 \"4x MSAA\" 4 \"8x MSAA\" 8\n"
"    range --show-value --status \"Adjust the brightness balance of game textures.\" \"texture gamma\" vid_gamma 1.3 0.3\n"
"    toggle --show-value --status \"Toggle use of monitor hardware for gamma correction.\" \"hardware gamma\" vid_hwgamma\n"
"    range --show-value --status \"Lower values increase texture detail (requires video restart).\" \"texture quality\" gl_picmip 3 0 -1\n"
"    pairs --status \"Choose between classic pixelated or modern smooth textures.\" \"texture filter\" gl_texturemode \\\n"
"        nearest GL_NEAREST \\\n"
"        linear GL_LINEAR \\\n"
"        bilinear GL_LINEAR_MIPMAP_NEAREST \\\n"
"        trilinear GL_LINEAR_MIPMAP_LINEAR\n"
"    pairs --show-value --status \"Improve texture clarity on surfaces viewed at an angle.\" \"anisotropic filter\" gl_anisotropy no 1 2x 2 4x 4 8x 8 16x 16\n"
"    range --show-value --status \"Adjust the color intensity of game world textures.\" \"texture saturation\" gl_saturation 0 1\n"
"    pairs --show-value --status \"Boost the overall brightness of textures.\" \"texture intensity\" intensity 1x 1 2x 2 3x 3\n"
"    range --show-value --status \"Adjust the color intensity of static lightmaps.\" \"lightmap saturation\" gl_coloredlightmaps 0 1\n"
"    range --show-value --status \"Fine-tune the brightness of static lighting.\" \"lightmap brightness\" gl_brightness 0 0.3\n"
"    values --status \"Legacy GL1.x vs Modern GL3.x shaders (requires video restart).\" \"rendering backend\" gl_shaders legacy shaders\n"
"    background #3f6da070\n"

"end\n"
"\n"
"begin options\n"
"    title \"Options\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    action --status \"Customize your player name and appearance.\" \"player setup\" pushmenu players\n"
"    action --status \"Configure jump-specific HUD and assist tools.\" \"jump setup\" pushmenu jump\n"
"    action --status \"Adjust mouse sensitivity and input settings.\" \"input setup\" pushmenu input\n"
"    action --status \"Bind movement and game actions to keys.\" \"key bindings\" pushmenu keys\n"
"    action --status \"Graphics, resolution, and quality settings.\" \"video setup\" pushmenu video\n"
"    action --status \"Audio levels and engine settings.\" \"sound setup\" pushmenu sound\n"
"    action --status \"Explosions, shadows, and rail trails.\" \"effects setup\" pushmenu effects\n"
"    action --status \"HUD size, opacity, and scaling.\" \"screen setup\" pushmenu screen\n"
"    action --status \"Asset downloading preferences.\" \"download options\" pushmenu downloads\n"
"    action --status \"Quick-connect address book.\" \"address book\" pushmenu addressbook\n"
"end\n"
"\n"
"begin sound\n"
"    title \"Sound Setup\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    values --status \"Select the audio output engine (OpenAL recommended).\" \"sound engine\" s_enable \"no sound\" \"software\" \"OpenAL\"\n"
"    range --show-value --status \"Lower values reduce delay but may cause stuttering.\" \"sound latency\" s_mixahead 0.05 0.2 --show-if s_enable !0\n"
"    range --show-value --status \"Overall volume of sound effects and voices.\" \"effects volume\" s_volume 0 1 --show-if s_enable !0\n"
"    range --show-value --status \"Volume level for background OGG music.\" \"music volume\" ogg_volume 0 1 --show-if ogg_enable !0\n"
"    toggle --status \"Enable or disable background music playback.\" \"enable music\" ogg_enable --show-if s_enable !0\n"
"    toggle --status \"Play music tracks in random order.\" \"shuffle tracks\" ogg_shuffle --show-if ogg_enable !0\n"
"    toggle --status \"Apply a muffled audio filter when submerged.\" \"underwater effect\" s_underwater --show-if s_enable !0\n"
"    values --status \"Ambient map sounds like wind or humming machinery.\" \"ambient sounds\" s_ambient \"no\" \"yes\" \"only player's own\" --show-if s_enable !0\n"
"    values --status \"Sound notification when receiving a chat message.\" \"chat beep\" cl_chat_sound \"disabled\" \"default\" \"alternative\" --show-if s_enable !0\n"
"end\n"
"\n"
"begin railtrail\n"
"    title \"Railgun Trail Setup\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    values --status \"Visual style of the railgun beam.\" \"rail trail type\" cl_railtrail_type \\\n"
"        \"default\" \"core only\" \"core and spiral\"\n"
"    range --show-value --status \"How long the trail remains visible in seconds.\" \"rail trail duration\" cl_railtrail_time 0.1 3.0 0.1\n"
"    range --show-value --status \"Thickness of the inner beam.\" \"core width\" cl_railcore_width 1 6 1\n"
"    range --show-value --status \"Spiral radius of the outer effect.\" \"spiral radius\" cl_railspiral_radius 1 6 1\n"
"    strings --status \"Color of the inner beam.\" \"core color\" cl_railcore_color \\\n"
"        black red green yellow blue cyan magenta white\n"
"    strings --status \"Color of the outer spiral.\" \"spiral color\" cl_railspiral_color \\\n"
"        black red green yellow blue cyan magenta white\n"
"end\n"
"\n"
"begin effects\n"
"    title \"Effects Setup\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    values --status \"World lighting from projectiles and explosions.\" \"dynamic lighting\" gl_dynamic \"no\" \"yes\" \"only switchable\"\n"
"    values --status \"Cartoon-style thick outlines on players and items.\" \"entity cel-shading\" gl_celshading no 1x 2x 3x\n"
"    toggle --status \"Enable glowing shell around certain entities.\" \"entity glowing\" cl_noglow ~\n"
"    values --status \"Drop-shadows under players and objects.\" \"ground shadows\" gl_shadows no yes fade\n"
"    toggle --status \"Screen tinting from items and environment (lava/water).\" \"screen blending\" gl_polyblend\n"
"    toggle --status \"Visual distortion effect when underwater.\" \"screen warping\" gl_waterwarp\n"
"    toggle --status \"Show or hide grenade explosion effects.\" \"grenade explosions\" cl_disable_explosions ~0\n"
"    toggle --status \"Show or hide rocket explosion effects.\" \"rocket explosions\" cl_disable_explosions ~1\n"
"    blank\n"
"    action --status \"Customize railgun beam colors and style.\" --align \"railgun trail setup...\" pushmenu railtrail\n"
"end\n"
"\n"
"begin crosshair\n"
"    title \"Crosshair Setup\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    values --status \"Style of the center-screen aiming cursor.\" \"crosshair type\" crosshair none cross dot angle\n"
"    pairs --status \"Change the physical size of the crosshair.\" \"crosshair scale\" ch_scale 0.5x 0.5 1x 1 2x 2 --show-if crosshair !0\n"
"    toggle --status \"Change crosshair color based on player health.\" \"color by health\" ch_health --show-if crosshair !0\n"
"    range --show-value --status \"Red intensity of the crosshair color.\" \"red channel\" ch_red 0 1 --show-if crosshair !0\n"
"    range --show-value --status \"Green intensity of the crosshair color.\" \"green channel\" ch_green 0 1 --show-if crosshair !0\n"
"    range --show-value --status \"Blue intensity of the crosshair color.\" \"blue channel\" ch_blue 0 1 --show-if crosshair !0\n"
"    range --show-value --status \"Opacity level of the crosshair.\" \"alpha channel\" ch_alpha 0 1 --show-if crosshair !0\n"
"end\n"
"\n"
"begin screen\n"
"    title \"Screen Setup\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    range --show-value --status \"Vertical field of view adjustment (legacy).\" \"screen size\" viewsize 40 100 10\n"
"    toggle --status \"Show a real-time graph of server latency.\" \"ping graph\" scr_lag_draw\n"
"    pairs --status \"Show a subtle network history indicator.\" \"network bar\" sh_netmeter off 0 lagometer 1 netgraph 2 histogram 3\n"
"    toggle --status \"Show short warnings for run-affecting network incidents.\" \"network notice\" sh_netalert\n"
"    values --status \"Detailed recording status bar for demos.\" \"demo bar\" scr_demobar no yes verbose\n"
"    pairs --show-value --status \"Text dump of frame/network errors.\" \"turtle text\" scr_showturtle off 0 normal 1 verbose 2\n"
"    range --show-value --status \"Overall transparency of the in-game HUD.\" \"HUD opacity\" scr_alpha 0 1\n"
"    range --show-value --status \"Transparency of the background console.\" \"console opacity\" con_alpha 0 1\n"
"    pairs --status \"Scale factor for all HUD elements.\" \"HUD scale\" scr_scale auto 0 1x 1 2x 2 4x 4\n"
"    pairs --status \"Scale factor for the console text.\" \"console scale\" con_scale auto 0 1x 1 2x 2 4x 4\n"
"    pairs --status \"Scale factor for this menu system.\" \"menu scale\" ui_scale auto 0 1x 1 2x 2 4x 4\n"
"    pairs --status \"Choose the menu source used after the next UI restart. Built-in ignores q2pro.menu; external file loads q2pro.menu overrides from disk.\" \"menu source\" ui_external_menu built-in 0 \"external file\" 1\n"
"    blank\n"
"    action --status \"Adjust aiming cursor appearance.\" --align \"crosshair setup...\" pushmenu crosshair\n"
"    action --status \"Configure jump-specific assist tools.\" --align \"jump HUD setup...\" pushmenu jump\n"
"end\n"
"\n"
"begin downloads\n"
"    title \"Download Options\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    toggle --status \"Global switch for automated server downloads.\" \"allow downloading\" allow_download\n"
"    toggle --status \"Automatically fetch missing .bsp files.\" \"maps\" allow_download_maps --show-if allow_download !0\n"
"    toggle --status \"Fetch custom player models and skins.\" \"player models/skins\" allow_download_players --show-if allow_download !0\n"
"    toggle --status \"Fetch custom 3D map objects and entities.\" \"models\" allow_download_models --show-if allow_download !0\n"
"    toggle --status \"Fetch custom weapon and ambient sounds.\" \"sounds\" allow_download_sounds --show-if allow_download !0\n"
"    toggle --status \"Fetch high-res or custom world textures.\" \"textures\" allow_download_textures --show-if allow_download !0\n"
"    toggle --status \"Fetch custom images, banners, and logos.\" \"pics\" allow_download_pics --show-if allow_download !0\n"
"    blank --show-if allow_download !0\n"
"    toggle --status \"Use high-speed web downloads where available.\" \"HTTP downloads\" cl_http_downloads --show-if allow_download !0\n"
"end\n"
"\n"
"begin jump\n"
"    title \"Jump Setup\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    blank\n"
"    action --status \"Configure the visual strafe-assist bar.\" \"strafe helper\" pushmenu strafehelper\n"
"    action --status \"Show your current speed (Units Per Second).\" \"UPS display\" pushmenu jumpups\n"
"    action --status \"Draw a trailing line behind your movement.\" \"race line\" pushmenu raceline\n"
"    action --status \"Configure subtle network history indicator.\" \"network bar\" pushmenu jumpnetwork\n"
"    action --status \"Configure on-screen network warning alerts.\" \"network alerts\" pushmenu jumpnetalerts\n"
"    action --status \"Bind keys for mod-specific actions.\" \"mod bindings\" pushmenu jumpmodbinds\n"
"    action --status \"Bind keys for quick FPS switching.\" \"fps bindings\" pushmenu jumpfpsbinds\n"
"    blank\n"
"    action --status \"Technical settings and debug commands.\" \"advanced/debug\" pushmenu jumpdebug\n"
"end\n"
"\n"
"begin jumpfpsbinds\n"
"    title \"FPS Bindings\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    \n"
"    bind --status \"Bind key to set cl_maxfps to 20.\" \"FPS 20\" f20\n"
"    bind --status \"Bind key to set cl_maxfps to 22.\" \"FPS 22\" f22\n"
"    bind --status \"Bind key to set cl_maxfps to 25.\" \"FPS 25\" f25\n"
"    bind --status \"Bind key to set cl_maxfps to 26.\" \"FPS 26\" f26\n"
"    bind --status \"Bind key to set cl_maxfps to 31.\" \"FPS 31\" f31\n"
"    bind --status \"Bind key to set cl_maxfps to 32.\" \"FPS 32\" f32\n"
"    bind --status \"Bind key to set cl_maxfps to 33.\" \"FPS 33\" f33\n"
"    bind --status \"Bind key to set cl_maxfps to 60.\" \"FPS 60\" f60\n"
"    bind --status \"Bind key to set cl_maxfps to 66.\" \"FPS 66\" f66\n"
"    bind --status \"Bind key to set cl_maxfps to 90.\" \"FPS 90\" f90\n"
"    bind --status \"Bind key to set cl_maxfps to 100.\" \"FPS 100\" f100\n"
"    bind --status \"Bind key to set cl_maxfps to 120.\" \"FPS 120\" f120\n"
"end\n"
"\n"
"begin jumpmodbinds\n"
"    title \"Mod Bindings\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    \n"
"    static \"[Movement / Storage]\"\n"
"    bind --status \"Saves current position and velocity.\" \"store\" store\n"
"    bind --status \"Returns to your stored position.\" \"recall\" recall\n"
"    bind --status \"Resets your current race run.\" \"reset\" reset\n"
"    bind --status \"Fires the grappling hook.\" \"hook\" hook\n"
"    bind --status \"Releases the grappling hook.\" \"unhook\" unhook\n"
"    blank\n"
"    \n"
"    static \"[HUD / Information]\"\n"
"    bind --status \"Toggles the replay statistics display.\" \"replay stats\" repstats\n"
"    bind --status \"Toggles jump distance announcement.\" \"show jumps\" showjumps\n"
"    bind --status \"Toggles split times display.\" \"show times\" showtimes\n"
"    bind --status \"Toggles checkpoint arrival sound.\" \"checkpoint sound\" cpsound\n"
"    bind --status \"Shows current frames per second.\" \"show FPS\" !fps\n"
"    blank\n"
"    \n"
"    static \"[Social / Team]\"\n"
"    bind --status \"Votes YES in current election.\" \"vote yes\" yes\n"
"    bind --status \"Votes NO in current election.\" \"vote no\" no\n"
"    bind --status \"Teleports you to a specific player.\" \"goto player\" goto\n"
"    bind --status \"Toggles your idle/AFK state.\" \"idle mode\" idle\n"
"    bind --status \"Joins the Easy difficulty team.\" \"join easy\" \"team easy\"\n"
"    bind --status \"Joins the Hard difficulty team.\" \"join hard\" \"team hard\"\n"
"    bind --status \"Moves you to the observer team.\" \"spectate\" observer\n"
"end\n"
"\n"
"begin jumpkeys\n"
"    title \"Jump Key Bindings\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    bind --status \"The primary jump action (+moveup).\" \"jump\" +moveup\n"
"    bind --status \"Double-jump script (+dj).\" \"double jump\" +dj\n"
"    bind --status \"Move downward or crouch (+movedown).\" \"crouch\" +movedown\n"
"    bind --status \"Move player forward (+forward).\" \"walk forward\" +forward\n"
"    bind --status \"Move player backward (+back).\" \"backpedal\" +back\n"
"    bind --status \"Side-step to the left (+moveleft).\" \"strafe left\" +moveleft\n"
"    bind --status \"Side-step to the right (+moveright).\" \"strafe right\" +moveright\n"
"    bind --status \"Return to the Jump Setup menu.\" \"jump setup menu\" \"pushmenu jump\"\n"
"    blank\n"
"    bind --status \"Toggle the scoreboard (score).\" \"scoreboard\" score\n"
"    bind --status \"Toggle the race timer (time).\" \"timer\" time\n"
"    bind --status \"Show current map coordinates (coord).\" \"coordinates\" coord\n"
"    bind --status \"Compare your time with best (compare).\" \"compare\" compare\n"
"    bind --status \"Clear the HUD of temporary messages (cleanhud).\" \"clear HUD\" cleanhud\n"
"    bind --status \"Toggle visibility of other players (ghost).\" \"toggle ghost\" ghost\n"
"end\n"
"\n"
"begin strafehelper\n"
"    title \"Strafe Helper\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    toggle --show-value --status \"Global switch for the strafe helper HUD element.\" \"enabled\" sh_draw\n"
"    toggle --show-value --status \"Show a central mark for neutral mouse position.\" \"center marker\" sh_centermarker --show-if sh_draw !0\n"
"    range --show-value --status \"Scale factor for the strafe helper bar.\" \"scale\" sh_scale 0.5 4.0 0.1 --show-if sh_draw !0\n"
"    range --show-value --status \"Vertical position from the top of the screen.\" \"Y position\" sh_y 0 320 5 --show-if sh_draw !0\n"
"    range --show-value --status \"Height of the strafe helper bar in pixels.\" \"height\" sh_height 4 80 1 --show-if sh_draw !0\n"
"    range --show-value --status \"Transparency of the strafe helper bar.\" \"alpha\" sh_alpha 0 1 0.05 --show-if sh_draw !0\n"
"    strings --show-value --status \"Visual drawing style of the strafe helper.\" \"bar style\" sh_bar_style gradient solid outline minimal --show-if sh_draw !0\n"
"    range --show-value --status \"Smooth visual movement of strafe helper angles; 0 disables it.\" \"smoothing\" sh_smoothing 0 10 0.1 --show-if sh_draw !0\n"
"    pairs --show-value --status \"Easing curve used by strafe helper smoothing.\" \"   smoothing mode\" sh_smoothing_mode linear 1 quadratic 2 cubic 3 sine 4 exponential 5 --show-if sh_draw !0 \n"
"    range --show-value --status \"Width of the center mouse position marker.\" \"center width\" sh_center_width 0.1 5 0.1 --show-if sh_draw !0\n"
"    range --show-value --status \"Width of the optimal acceleration zone.\" \"optimal width\" sh_optimal_width 0.1 5 0.1 --show-if sh_draw !0\n"
"    toggle --show-value --status \"Draw the optimal angle marker as an outline.\" \"optimal outline\" sh_optimal_outline --show-if sh_draw !0\n"
"    field --picker --status \"Color when mouse is within optimal zone.\" \"accelerating color\" sh_color_accelerating --show-if sh_draw !0\n"
"    field --picker --status \"Color when moving at perfect angle.\" \"optimal color\" sh_color_optimal --show-if sh_draw !0\n"
"    field --picker --status \"Color of the center neutral marker.\" \"center marker color\" sh_color_centermarker --show-if sh_draw !0\n"
"    blank --show-if sh_draw !0\n"
"    action --status \"Choose from a set of pre-defined color schemes.\" --align \"apply color preset...\" pushmenu shpresets --show-if sh_draw !0\n"
"end\n"
"\n"
"begin shpresets\n"
"    title \"Strafe Helper Presets\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    action --status \"Apply a randomized color scheme.\" \"random\" \"sh hud preset random\"\n"
"    action --status \"Original grey and blue theme.\" \"vanilla\" \"sh hud preset vanilla\"\n"
"    action --status \"Calm blue and teal tones.\" \"ocean\" \"sh hud preset ocean\"\n"
"    action --status \"Classic CRT orange and green.\" \"retro\" \"sh hud preset retro\"\n"
"    action --status \"Neon pink and cyan aesthetic.\" \"cyberpunk\" \"sh hud preset cyberpunk\"\n"
"    action --status \"Fresh green and white theme.\" \"mint\" \"sh hud preset mint\"\n"
"    action --status \"Hot orange and red theme.\" \"lava\" \"sh hud preset lava\"\n"
"    action --status \"Subtle dark and grey tones.\" \"shadow\" \"sh hud preset shadow\"\n"
"    action --status \"List all available presets in the console.\" \"show all presets\" \"sh hud preset\"\n"
"end\n"
"\n"
"begin jumpups\n"
"    title \"UPS Display\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    toggle --show-value --status \"Show current movement speed (Units Per Second).\" \"enabled\" sh_ups\n"
"    range --show-value --status \"Scale factor for the speed digits.\" \"scale\" sh_ups_scale 0.25 4 0.25 --show-if sh_ups !0\n"
"    range --show-value --status \"Vertical offset from screen center.\" \"Y position\" sh_ups_y -300 300 5 --show-if sh_ups !0\n"
"    toggle --show-value --status \"Draw a drop-shadow behind the speed digits.\" \"shadow\" sh_ups_shadow --show-if sh_ups !0\n"
"    toggle --show-value --status \"Hide the display when speed is zero.\" \"hide zero\" sh_ups_hide_zero --show-if sh_ups !0\n"
"    toggle --show-value --status \"Include vertical velocity component in calculations.\" \"3D speed\" sh_ups_3d --show-if sh_ups !0\n"
"    strings --show-value --status \"How speed changes affect text color.\" \"color mode\" sh_ups_color_mode dynamic static threshold rainbow gradient strafing --show-if sh_ups !0\n"
"    strings --show-value --status \"Display speed as raw number or with label.\" \"format\" sh_ups_format plain suffix prefix --show-if sh_ups !0\n"
"    field --picker --status \"Color used when gaining speed.\" \"gain color\" sh_ups_color_gain --show-if sh_ups !0\n"
"    field --picker --status \"Color used when losing speed.\" \"loss color\" sh_ups_color_loss --show-if sh_ups !0\n"
"    field --picker --status \"Color used when at constant speed.\" \"neutral color\" sh_ups_color_neutral --show-if sh_ups !0\n"
"end\n"
"\n"
"begin raceline\n"
"    title \"Race Line\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    range --show-value --status \"Thickness of the movement trail line.\" \"width\" race_width 0 20 1\n"
"    range --show-value --status \"Opacity level of the movement trail.\" \"opacity\" race_alpha 0 1 0.05\n"
"    range --show-value --status \"Duration before the line fades away (ms).\" \"lifetime (ms)\" race_life 0 5000 100\n"
"    field --picker --status \"Color of the movement trail line.\" \"line color\" race_color\n"
"end\n"
"\n"
"begin jumpnetwork\n"
"    title \"Jump Network\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    static \"[Run Feedback]\"\n"
"    pairs --show-value --status \"Localized network status indicator.\" \"network bar\" sh_netmeter off 0 lagometer 1 netgraph 2 histogram 3\n"
"    pairs --show-value --status \"Scale netmeter dynamically based on recent latency baseline.\" \"adaptive scaling\" sh_netmeter_adaptive off 0 on 1 --show-if sh_netmeter !0\n"
"    range --show-value --status \"Minimum latency scaling threshold in milliseconds.\" \"min latency\" sh_netmeter_min_ms 0 1000 10 --show-if sh_netmeter_adaptive 0\n"
"    range --show-value --status \"Maximum latency scaling threshold in milliseconds.\" \"max latency\" sh_netmeter_max_ms 0 1000 10 --show-if sh_netmeter_adaptive 0\n"
"    blank --show-if sh_netmeter !0\n"
"    static \"[Lagometer Layout]\" --show-if sh_netmeter 1\n"
"    range --show-value --status \"Horizontal offset; negative values align from the right edge.\" \"X position\" sh_lagometer_x -640 640 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Vertical offset; negative values align from the bottom edge.\" \"Y position\" sh_lagometer_y -480 480 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Opacity of normal samples; lower values keep stable network almost invisible.\" \"normal alpha\" sh_lagometer_alpha 0 1 0.05 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Opacity of loss/stall/prediction samples.\" \"incident alpha\" sh_lagometer_bad_alpha 0 1 0.05 --show-if sh_netmeter 1\n"
"    blank --show-if sh_netmeter 1\n"
"    static \"[Lagometer Theme & Colors]\" --show-if sh_netmeter 1\n"
"    range --show-value --status \"Normal packet color palette index.\" \"normal color\" sh_lagometer_color_normal 0 255 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Ping spike color palette index.\" \"spike color\" sh_lagometer_color_spike 0 255 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Ping jitter color palette index.\" \"jitter color\" sh_lagometer_color_jitter 0 255 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Incoming (Server-to-Client) packet loss color palette index.\" \"S2C loss color\" sh_lagometer_color_loss_s2c 0 255 1 --show-if sh_netmeter 1\n"
"    range --show-value --status \"Outgoing (Client-to-Server) packet loss color palette index.\" \"C2S loss color\" sh_lagometer_color_loss_c2s 0 255 1 --show-if sh_netmeter 1\n"
"    blank --show-if sh_netmeter 1\n"
"    static \"[Netgraph Layout]\" --show-if sh_netmeter 2\n"
"    range --show-value --status \"Bar height in HUD pixels.\" \"height\" sh_netgraph_height 1 120 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Vertical offset; negative values align from the bottom edge.\" \"Y position\" sh_netgraph_y -480 480 1 --show-if sh_netmeter 2\n"
"    blank --show-if sh_netmeter 2\n"
"    static \"[Netgraph Theme & Colors]\" --show-if sh_netmeter 2\n"
"    range --show-value --status \"Normal packet color palette index.\" \"normal color\" sh_netgraph_color_normal 0 255 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Ping spike color palette index.\" \"spike color\" sh_netgraph_color_spike 0 255 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Ping jitter color palette index.\" \"jitter color\" sh_netgraph_color_jitter 0 255 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Incoming (Server-to-Client) packet loss color palette index.\" \"S2C loss color\" sh_netgraph_color_loss_s2c 0 255 1 --show-if sh_netmeter 2\n"
"    range --show-value --status \"Outgoing (Client-to-Server) packet loss color palette index.\" \"C2S loss color\" sh_netgraph_color_loss_c2s 0 255 1 --show-if sh_netmeter 2\n"
"    blank --show-if sh_netmeter 2\n"
"    static \"[Histogram Layout]\" --show-if sh_netmeter 3\n"
"    range --show-value --status \"Bar height in HUD pixels.\" \"height\" sh_histogram_height 1 120 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Bar width in HUD pixels.\" \"width\" sh_histogram_width 10 640 10 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Horizontal offset; negative values align from the right edge.\" \"X position\" sh_histogram_x -640 640 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Vertical offset; negative values align from the bottom edge.\" \"Y position\" sh_histogram_y -480 480 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Opacity of normal samples; lower values keep stable network almost invisible.\" \"normal alpha\" sh_histogram_alpha 0 1 0.05 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Opacity of loss/stall/prediction samples.\" \"incident alpha\" sh_histogram_bad_alpha 0 1 0.05 --show-if sh_netmeter 3\n"
"    range --show-value --status \"How much recent history the bar represents, in milliseconds.\" \"history ms\" sh_histogram_history_ms 500 120000 1000 --show-if sh_netmeter 3\n"
"    toggle --show-value --status \"Draw current ping value over the histogram.\" \"ping display\" sh_histogram_ping --show-if sh_netmeter 3\n"
"    blank --show-if sh_netmeter 3\n"
"    static \"[Histogram Theme & Colors]\" --show-if sh_netmeter 3\n"
"    range --show-value --status \"Histogram background opacity level.\" \"background alpha\" sh_histogram_bg_alpha 0 1 0.05 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Histogram background color palette index.\" \"background color\" sh_histogram_color_bg 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Normal packet color palette index.\" \"normal color\" sh_histogram_color_normal 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Ping spike color palette index.\" \"spike color\" sh_histogram_color_spike 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Ping jitter color palette index.\" \"jitter color\" sh_histogram_color_jitter 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Incoming (Server-to-Client) packet loss color palette index.\" \"S2C loss color\" sh_histogram_color_loss_s2c 0 255 1 --show-if sh_netmeter 3\n"
"    range --show-value --status \"Outgoing (Client-to-Server) packet loss color palette index.\" \"C2S loss color\" sh_histogram_color_loss_c2s 0 255 1 --show-if sh_netmeter 3\n"
"    blank --show-if sh_netmeter 3\n"
"    action --status \"Configure latency and loss warning thresholds.\" \"threshold settings\" pushmenu jumpnetthresholds\n"
"end\n"
"\n"
"begin jumpnetalerts\n"
"    title \"Network Alerts\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    static \"[Notice Feedback]\"\n"
"    toggle --show-value --status \"Short warning text for incidents likely to affect a run.\" \"incident notice\" sh_netalert\n"
"    blank --show-if sh_netalert !0\n"
"    static \"[Notice Layout]\" --show-if sh_netalert !0\n"
"    range --show-value --status \"Incident notice horizontal offset.\" \"notice X\" sh_netalert_x -640 640 1 --show-if sh_netalert !0\n"
"    range --show-value --status \"Incident notice vertical offset; negative values align from the bottom edge.\" \"notice Y\" sh_netalert_y -480 480 1 --show-if sh_netalert !0\n"
"    range --show-value --status \"Alert text color code (1=red, 2=green, 3=yellow, 4=blue, 5=cyan, 6=magenta, 7=severity-based, 8=orange, 9=purple).\" \"notice color\" sh_netalert_color 1 9 1 --show-if sh_netalert !0\n"
"    range --show-value --status \"How long incident text stays visible, in milliseconds.\" \"notice ms\" sh_netalert_duration_ms 250 5000 250 --show-if sh_netalert !0\n"
"    range --show-value --status \"Opacity of incident notice text.\" \"notice alpha\" sh_netalert_alpha 0 1 0.05 --show-if sh_netalert !0\n"
"    blank --show-if sh_netalert !0\n"
"    static \"[Notice Types]\" --show-if sh_netalert !0\n"
"    toggle --show-value --status \"Show notice for dropped packets.\" \"loss notice\" sh_netalert_loss --show-if sh_netalert !0\n"
"    toggle --show-value --status \"Show notice for repeated ping wobble.\" \"jitter notice\" sh_netalert_jitter --show-if sh_netalert !0\n"
"    toggle --show-value --status \"Show notice for sudden ping jumps.\" \"spike notice\" sh_netalert_spike --show-if sh_netalert !0\n"
"    blank --show-if sh_netalert !0\n"
"    action --status \"Configure latency and loss warning thresholds.\" \"threshold settings\" pushmenu jumpnetthresholds --show-if sh_netalert !0\n"
"    blank --show-if sh_netalert !0\n"
"end\n"
"\n"
"begin jumpnetthresholds\n"
"    title \"Network Thresholds\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    static \"[Latency Thresholds]\"\n"
"    toggle --show-value --status \"Compare spikes and jitter against your current ping baseline; recommended for distant servers.\" \"adaptive ping\" sh_netwarn_ping_adaptive\n"
"    range --show-value --status \"Minimum sudden ping jump before a spike warning.\" \"spike ms\" sh_netwarn_spike_ms 0 300 5 --show-if sh_netwarn_ping_adaptive 0\n"
"    range --show-value --status \"Adaptive spike threshold as percent of your rolling ping baseline.\" \"spike pct\" sh_netwarn_spike_pct 0 100 5 --show-if sh_netwarn_ping_adaptive 1\n"
"    range --show-value --status \"Repeated ping wobble threshold before jitter warning.\" \"jitter ms\" sh_netwarn_jitter_ms 0 150 5\n"
"    blank\n"
"end\n"
"\n"
"begin replayrecording\n"
"    title \"Replay Recording\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    action --status \"Start recording a new movement replay.\" \"start recording\" \"sh record\"\n"
"    action --status \"Stop the current recording session.\" \"stop recording\" \"sh stop\"\n"
"    action --status \"Play back a saved movement replay.\" \"play replay\" \"sh play\"\n"
"end\n"
"\n"
"begin jumpdebug\n"
"    title \"Jump Debug\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent --live\n"
"    pairs --status \"Diagnostic overlay for movement physics.\" \"NerdStats\" sh_nerdstats off 0 left 1 right 2\n"
"    action --status \"Report current strafe helper internal state.\" --align \"show strafe helper status\" \"sh status\"\n"
"    action --status \"List all active jump-mod commands.\" --align \"show commands\" !help\n"
"    bind --status  \"debug physic.\" --align \"dump physics now\" debugnow\n"
"end\n"
"\n"
"begin multiplayer\n"
"    title \"Multiplayer\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    action --status \"Browse all active Quake 2 servers.\" \"browse q2servers.com\" pushmenu servers \"+http://q2servers.com/?raw=2\"\n"
"    action --status \"Find active jump and race servers.\" \"browse jump servers\" pushmenu servers \"@jump +http://q2servers.com/?raw=2&mod=jump\"\n"
"    action --status \"Quick access to your saved servers.\" \"browse address book\" pushmenu servers \"favorites://\" \"file:///servers.lst\" \"broadcast://\"\n"
"    action --status \"Watch recorded match and jump replays.\" \"browse demos\" pushmenu demos\n"
"end\n"
"\n"
"begin main\n"
"    title \"Main Menu\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    action --status \"Find and join online games.\" \"multiplayer\" pushmenu multiplayer\n"
"    action --status \"Engine and gameplay configuration.\" \"options\" pushmenu options\n"
"    action --status \"Display and resolution settings.\" \"video setup\" pushmenu video\n"
"    blank\n"
"    action --status \"Exit the game.\" \"quit\" quit\n"
"end\n"
"\n"
"begin game\n"
"    title \"In-Game Menu\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    action --status \"Configure HUD and jump tools.\" \"jump setup\" pushmenu jump\n"
"    blank\n"
"    action --status \"Find active jump and race servers.\" \"browse jump servers\" pushmenu servers \"@jump +http://q2servers.com/?raw=2&mod=jump\"\n"
"    action --status \"Quick access to your saved servers.\" \"browse address book\" pushmenu servers \"favorites://\" \"file:///servers.lst\" \"broadcast://\"\n"
"    action --status \"Browse all active Quake 2 servers.\" \"browse q2servers.com\" pushmenu servers \"+http://q2servers.com/?raw=2\"\n"
"    action --status \"Watch recorded match and jump replays.\" \"browse demos\" pushmenu demos\n"
"    action --status \"Engine and gameplay configuration.\" \"options\" pushmenu options\n"
"    blank\n"
"    action --status \"Leave the current server.\" \"disconnect\" disconnect\n"
"    action --status \"Exit the game.\" \"quit\" quit\n"
"end\n"
"\n"
"begin addressbook\n"
"    //title \"Address Book\"\n"
"    banner m_banner_addressbook\n"
"    field --width 32 --center --status \"Favorite server address slot 0.\" adr0\n"
"    field --width 32 --center --status \"Favorite server address slot 1.\" adr1\n"
"    field --width 32 --center --status \"Favorite server address slot 2.\" adr2\n"
"    field --width 32 --center --status \"Favorite server address slot 3.\" adr3\n"
"    field --width 32 --center --status \"Favorite server address slot 4.\" adr4\n"
"    field --width 32 --center --status \"Favorite server address slot 5.\" adr5\n"
"    field --width 32 --center --status \"Favorite server address slot 6.\" adr6\n"
"    field --width 32 --center --status \"Favorite server address slot 7.\" adr7\n"
"    field --width 32 --center --status \"Favorite server address slot 8.\" adr8\n"
"    field --width 32 --center --status \"Favorite server address slot 9.\" adr9\n"
"    field --width 32 --center --status \"Favorite server address slot 10.\" adr10\n"
"    field --width 32 --center --status \"Favorite server address slot 11.\" adr11\n"
"    field --width 32 --center --status \"Favorite server address slot 12.\" adr12\n"
"    field --width 32 --center --status \"Favorite server address slot 13.\" adr13\n"
"    field --width 32 --center --status \"Favorite server address slot 14.\" adr14\n"
"    field --width 32 --center --status \"Favorite server address slot 15.\" adr15\n"
"end\n"
"\n"
"begin input\n"
"    title \"Input Setup\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    field --numeric --width 8 --status \"Multiplier for mouse movement speed.\" \"mouse sens\" sensitivity\n"
"    toggle --status \"Automatically scale sensitivity based on resolution.\" \"auto sens\" m_autosens\n"
"    toggle --status \"Smooth out erratic mouse movement.\" \"mouse filter\" m_filter\n"
"    toggle --status \"Use the mouse to aim around (recommended).\" \"free look\" freelook\n"
"    toggle --status \"Player always moves at running speed.\" \"always run\" cl_run\n"
"    values --status \"Change OS cursor style for game window.\" \"system cursor\" win_menu_cursor arrow cross hand ibeam wait no size\n"
"    values --status \"Change texture for in-game menu cursor.\" \"menu cursor texture\" cl_menu_cursor none cross dot angle\n"
"end\n"
"\n"
"begin keys\n"
"    title \"Key Bindings\"\n"
"    background #3f6da070\n"
"    style --compact --center --transparent\n"
"    bind --status \"Fire current weapon.\" \"attack\" +attack\n"
"    bind --status \"Move the player forward.\" \"walk forward\" +forward\n"
"    bind --status \"Move the player backward.\" \"backpedal\" +back\n"
"    bind --status \"Hold to walk or run (depending on settings).\" \"run\" +speed\n"
"    bind --status \"Side-step to the left.\" \"step left\" +moveleft\n"
"    bind --status \"Side-step to the right.\" \"step right\" +moveright\n"
"    bind --status \"Jump upward.\" \"up / jump\" +moveup\n"
"    bind --status \"Double-jump script (+dj).\" \"double jump\" +dj\n"
"    bind --status \"Crouch/duck\" \"down / crouch\" +movedown\n"
"    bind --status \"Open the items and equipment list.\" \"inventory\" inven\n"
"    bind --status \"Activate the currently selected item.\" \"use item\" invuse\n"
"    bind --status \"Discard the currently selected item.\" \"drop item\" invdrop\n"
"    bind --status \"Highlight previous inventory item.\" \"prev item\" invprev\n"
"    bind --status \"Highlight next inventory item.\" \"next item\" invnext\n"
"    bind --status \"Display current objective or help.\" \"help computer\" help\n"
"    bind --status \"Toggle the match statistics display.\" \"scoreboard\" score\n"
"    bind --status \"Open the global chat console.\" \"chat\" messagemode\n"
"    blank\n"
"    action --status \"Bindings for keyboard-only aiming and turning.\" --align \"legacy keys...\" pushmenu legacykeys\n"
"end\n"
"\n"
"begin legacykeys\n"
"    title \"Legacy Key Bindings\"\n"
"    background #3f6da040\n"
"    style --compact --center --transparent\n"
"    bind --status \"Rotate view to the left (keyboard).\" \"turn left\" +left\n"
"    bind --status \"Rotate view to the right (keyboard).\" \"turn right\" +right\n"
"    bind --status \"Modifier for keyboard-driven strafing.\" \"sidestep\" +strafe\n"
"    bind --status \"Tilt view upward (keyboard).\" \"look up\" +lookup\n"
"    bind --status \"Tilt view downward (keyboard).\" \"look down\" +lookdown\n"
"    bind --status \"Snap view back to horizon level.\" \"center view\" centerview\n"
"    bind --status \"Enable mouse-driven aiming (legacy).\" \"mouse look\" +mlook\n"
"    bind --status \"Enable keyboard-driven aiming (legacy).\" \"keyboard look\" +klook\n"
"end\n"

;
