name: build

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - q2pro_race
      - dev

env:
  MESON_ARGS: >-
    --auto-features=enabled
    --fatal-meson-warnings
    -Danticheat-server=true
    -Davcodec=enabled
    -Dclient-gtv=true
    -Dpacketdup-hack=true
    -Dvariable-fps=true


  MESON_ARGS_WIN: >-
    -Dsdl2=disabled
    -Dwayland=disabled
    -Dwrap_mode=forcefallback
    -Dx11=disabled


jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - arch: x64
            msystem: MINGW64
            package-prefix: mingw-w64-x86_64
          - arch: x86
            msystem: MINGW32
            package-prefix: mingw-w64-i686
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - uses: actions/cache@v4
        with:
          path: subprojects/packagecache
          key: ${{ hashFiles('subprojects/*.wrap') }}

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.package-prefix }}-ffmpeg
            ${{ matrix.package-prefix }}-gcc
            ${{ matrix.package-prefix }}-meson
            ${{ matrix.package-prefix }}-nasm
            ${{ matrix.package-prefix }}-ninja
            ${{ matrix.package-prefix }}-pkgconf

      - name: Build
        run: |
          meson setup ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_WIN }} builddir-${{ matrix.arch }} --buildtype=release
          meson compile -C builddir-${{ matrix.arch }}

      - name: Collect artifacts
        run: |
          mkdir -p artifacts/jump/pics
          cp builddir-${{ matrix.arch }}/q2pro_race.exe artifacts/
          ldd artifacts/q2pro_race.exe | awk '/\/mingw/ { print $3 }' | sort -u | xargs -r cp -t artifacts/
          cp jump/pics/prochars.png artifacts/jump/pics/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 2
          name: q2pro_race-windows-${{ matrix.arch }}
          path: artifacts

  release:
    needs: [windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: q2pro_race-*
          path: artifacts

      - name: Compress release artifacts
        run: |
          for dir in artifacts/q2pro_race-*; do
            (cd "$dir" && zip -r "../$(basename "$dir").zip" .)
          done

      - name: Create or update "latest" release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view latest --json name --jq .name >/dev/null 2>&1; then
            echo "Updating 'latest' release"
            gh release edit latest -t "Latest" -n "Automatically updated latest build" --latest
            gh release upload latest ./artifacts/*.zip --clobber
          else
            echo "Creating latest release"
            gh release create latest ./artifacts/*.zip --title "Latest" --notes "Automatically updated latest build"
          fi
      - name: Update tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/latest",
              sha: context.sha,
              force: true
            })
